// Cole aqui os dados do seu projeto Supabase (Project Settings > API)
export const SUPABASE_URL = sb_publishable_KWn09AMF3u_ye2-uvTxN8A_dl9vRdUa;
export const SUPABASE_KEY = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFuYWh5endteWVucHp2b2FtdGNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTEwNzQ4NTMsImV4cCI6MjEwNjY1MDg1M30.tntObX0r9zQx9GczN853STfN0SeWH6VDRpwhsyFGdxY;
